conf/application.conf

Content security policy blocked access to contact frontend in local

CDSID-471 | fixed content security policy

---

app/views/upload_your_files_receipt.scala.html
conf/messages

Upadte content to match new content in story

---

app/views/how_many_files_upload.scala.html
app/views/mrn_entry.scala.html

The error message position has been updated upon both pages
https://jira.tools.tax.service.gov.uk/browse/CEDS-2381

CEDS-2381 - Update Error Layout

---

app/Module.scala
app/connectors/AnswersConnector.scala
app/connectors/CustomsDeclarationsConnector.scala
app/connectors/UpscanConnector.scala
app/controllers/UploadYourFilesReceiptController.scala
app/controllers/UpscanStatusController.scala
app/controllers/actions/AuthAction.scala
app/controllers/actions/ContactDetailsRequiredAction.scala
app/controllers/actions/DataRetrievalAction.scala
app/controllers/actions/FileUploadResponseRequiredAction.scala
app/filters/CustomFrontendFilters.scala
app/filters/FilterWithWhitelist.scala
app/filters/WhitelistFilter.scala
app/metrics/SfusMetrics.scala
app/services/CustomsDeclarationsService.scala
conf/app.routes
conf/application.conf
test/base/SfusMetricsMock.scala
test/base/SpecBase.scala
test/connectors/UpscanConnectorTest.scala
test/controllers/UploadYourFilesReceiptControllerSpec.scala
test/controllers/UpscanStatusControllerSpec.scala
test/services/CustomsDeclarationsServiceSpec.scala

Added timers for:
- fetching notifications from backend
- file upload to upscan-proxy
- file upload request to customs-declarations
Added counters for:
- file upload to upscan-proxy
- file upload to customs-declarations

CEDS-2384 Add metrics

---

app/config/ExternalServicesConfig.scala
app/views/components/link.scala.html
app/views/contact_details.scala.html
app/views/how_many_files_upload.scala.html
app/views/mrn_entry.scala.html
app/views/start.scala.html
app/views/unauthorised.scala.html
app/views/upload_your_files.scala.html
app/views/upload_your_files_receipt.scala.html
conf/application.conf
conf/messages
test/base/SpecBase.scala
test/views/UnauthorisedSpec.scala
test/views/UploadYourFilesReceiptSpec.scala

Removed support phone numbers for all pages

CEDS-2575 - update unauthorised content

---

app/controllers/actions/AuthAction.scala
app/filters/AllowListFilter.scala
app/filters/FilterWithAllowList.scala
conf/application.conf
test/controllers/actions/AuthActionSpec.scala
test/controllers/actions/EORIActionSpec.scala
test/filters/AllowListFilterSpec.scala

Change code occurrences of 'whitelist' to 'allow list'

CEDS-2674 Replace 'whitelist' and 'blacklist' across services

---

app/repositories/AnswersRepository.scala
app/repositories/RepositorySettings.scala

This is in order to increase resilience of the service.

CEDS-2776 Implement FailoverStrategy for all repository classes

---

app/controllers/test/CustomsDeclarationsStubController.scala

www.staging.upscan.tax.service.gov.uk will be allowed by infrastruture.

CEDS-2798 Revert changes

---

app/views/main_template.scala.html
app/views/start.scala.html

GDS pages have it implemented already.

CEDS-2936 Implement 'Get help' link for all non-GDS pages

---

app/views/components/gds/gdsMainTemplate.scala.html

We should be creating these footer items dynamically instead of adding
them programmatically.

CEDS-2935 Add Accessibility footer link on GDS template

---

build.sbt
project/plugins.sbt
test/base/SpecBase.scala
test/connectors/UpscanConnectorTest.scala

Upgrade service to Play 2.7.9 and update dependencies

CEDS-2940 Upgrade to Play 2.7

---

app/controllers/ContactDetailsController.scala
app/controllers/HowManyFilesUploadController.scala
app/controllers/MrnEntryController.scala
app/controllers/StartController.scala
app/controllers/actions/ContactDetailsRequiredAction.scala
app/controllers/actions/MrnRequiredAction.scala
app/models/UserAnswers.scala
app/models/requests/ContactDetailsRequest.scala
app/models/requests/MrnRequest.scala
conf/app.routes
test/controllers/ContactDetailsControllerSpec.scala
test/controllers/MrnEntryControllerSpec.scala
test/controllers/StartControllerSpec.scala
test/controllers/actions/FakeActions.scala

Reorder journey so that MRN Entry is after Start page. 
New journey is:
1. /start
2. /mrn-entry
3. /contact-details
4. /how-many-files-upload

CEDS-2962 Reorder MRN Entry

---

app/config/ErrorHandler.scala
app/connectors/CdsFileUploadConnector.scala
app/controllers/ChoiceController.scala
app/controllers/ErrorPageController.scala
app/controllers/StartController.scala
app/controllers/actions/SecureMessagingFeatureAction.scala
app/forms/ChoiceForm.scala
app/forms/mappings/EnhancedMapping.scala
app/forms/validators/FieldValidator.scala
app/models/exceptions/InvalidFeatureStateException.scala
app/views/choice_page.scala.html
app/views/components/gds/errorSummary.scala.html
app/views/error_template.scala.html
app/views/not_implemented.scala.html
conf/app.routes
conf/messages
test/base/TestRequests.scala
test/controllers/ChoiceControllerSpec.scala
test/controllers/ErrorPageControllerSpec.scala
test/controllers/StartControllerSpec.scala
test/controllers/actions/FakeActions.scala
test/controllers/actions/SecureMessagingFeatureActionSpec.scala
test/forms/ChoiceFormSpec.scala
test/forms/validators/FieldValidatorSpec.scala
test/views/ChoicePageSpec.scala

This PR adds /what-do-you-want-to-do page
(aka. ChoicePage).
Secure Messaging Inbox pages are not implemented
yet, therefore a placeholder page is in place.
Both new endpoints are "hidden" behind a feature flag.

CEDS-3021 choice page

---

app/config/AppConfig.scala
app/connectors/SecureMessageFrontendConnector.scala
app/controllers/ChoiceController.scala
app/controllers/SecureMessagingController.scala
app/controllers/actions/SecureMessagingFeatureAction.scala
app/models/SecureMessagePartial.scala
app/views/messaging/partial_wrapper.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/base/AppConfigMockHelper.scala
test/config/AppConfigSpec.scala
test/connectors/SecureMessageFrontendConnectorSpec.scala
test/controllers/ChoiceControllerSpec.scala
test/controllers/SecureMessagingControllerSpec.scala
test/controllers/actions/FakeActions.scala
test/controllers/actions/SecureMessagingFeatureActionSpec.scala
test/views/messaging/PartialWrapperSpec.scala

Adding the new message inbox to the service that is
linked to from the new 'what_do_you_want_to_do' choice
page.

[CEDS-3024] Adding two way messaging service inbox

---

app/config/AppConfig.scala
app/connectors/SecureMessageFrontendConnector.scala
app/controllers/ChoiceController.scala
app/controllers/SecureMessagingController.scala
app/views/messaging/conversation_wrapper.scala.html
app/views/messaging/inbox_wrapper.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/config/AppConfigSpec.scala
test/connectors/SecureMessageFrontendConnectorSpec.scala
test/controllers/ChoiceControllerSpec.scala
test/controllers/SecureMessagingControllerSpec.scala
test/views/messaging/ConversationWrapperSpec.scala
test/views/messaging/InboxWrapperSpec.scala

Also renamed the old 'conversations' view to 'inbox'.

[CEDS-3037] Add view individual messages screen for TWSM

---

app/connectors/SecureMessageFrontendConnector.scala
test/connectors/SecureMessageFrontendConnectorSpec.scala

Enabling the connector to communicate with the
secure-message-frontend service for retrieval
of the inbox partial.

CEDS-3066 Conversation inbox integration

---

app/connectors/SecureMessageFrontendConnector.scala
test/connectors/SecureMessageFrontendConnectorSpec.scala

Retrieve the "Conversation" partial from the downstream service

CEDS-3067 Retrieve the "Conversation" partial 

---

conf/messages

Update the link's text in the the "Conversation" page's right grey box

CEDS-3062 Update the link's text

---

app/connectors/SecureMessageFrontendConnector.scala
app/controllers/SecureMessagingController.scala
conf/app.routes
test/connectors/SecureMessageFrontendConnectorSpec.scala
test/controllers/SecureMessagingControllerSpec.scala

Adding to the connector the code to call the secure-message-frontend
POST reply and GET result endpoints.

[CEDS-3068] Post Reply and Reply Success endpoint integration

---

app/forms/mappings/Constraints.scala
app/forms/mappings/ContactDetailsMapping.scala
app/models/ContactDetails.scala
app/services/AuditService.scala
app/views/contact_details.scala.html
conf/messages
test/connectors/UpscanConnectorTest.scala
test/controllers/ContactDetailsControllerSpec.scala
test/controllers/UpscanStatusControllerSpec.scala
test/forms/mappings/ContactDetailsMappingSpec.scala
test/generators/Generators.scala
test/services/AuditServiceSpec.scala
test/testdata/CommonTestData.scala
test/views/ContactDetailsSpec.scala

Removing email field from the UI and the underlying model.

[CEDS-3120] Remove email field from contact details page

---

app/controllers/UploadYourFilesReceiptController.scala
app/models/Notification.scala
test/connectors/CdsFileUploadConnectorSpec.scala
test/controllers/UploadYourFilesReceiptControllerSpec.scala
test/controllers/UpscanStatusControllerSpec.scala

This is to align the model with the wco schema.

CEDS-3457 Make NotificationDetails.filename optional

---

app/connectors/CdsFileUploadConnector.scala
app/controllers/UnverifiedEmailController.scala
app/controllers/actions/VerifiedEmailAction.scala
app/models/Email.scala
app/views/undeliverable_email.scala.html
conf/app.routes
conf/messages
test/connectors/CdsFileUploadConnectorSpec.scala
test/controllers/UnverifiedEmailControllerSpec.scala
test/controllers/actions/VerifiedEmailActionSpec.scala

Add ability to show error/help page when a user tries to use the service with an email address that is undeliverable.

CEDS-3620 Add undeliverable email page and model

---

conf/application.conf

To meet splunk storage requirements.

CEDS-3650 Add config to stop auditing of asset requests

---

app/assets/stylesheets/partials/_print-page.scss
app/controllers/InboxChoiceController.scala
app/controllers/UploadYourFilesReceiptController.scala
app/repositories/ZonedDateTimeFormat.scala
app/views/components/feedback_section.scala.html
app/views/components/gds/gdsMainTemplate.scala.html
app/views/components/gds/navigationBanner.scala.html
app/views/upload_your_files_confirmation.scala.html
project/plugins.sbt
test/unit/controllers/InboxChoiceControllerSpec.scala
test/unit/services/SecureMessageAnswersServiceSpec.scala

Added a few tests, not related to the ticket, in order to increase the coverage threshold.

CEDS-5009 Refactoring of the receipt page when printed

---

app/controllers/SecureMessagingController.scala

Remove UTF-8 encoding that is not accepted by new RedirectUrl class.

CEDS-5079 Navigation landmarks issue fix

---

app/connectors/SecureMessageFrontendConnector.scala
test/connectors/SecureMessageFrontendConnectorSpec.scala

Do not sent the notificationType query parameter if there is no filter value selected

CEDS-6214_SFUS_mesage_filter_issue
