hmrc/cds-file-upload-frontend

conf/application.conf

This is a Temporary fix for the tests. It removes the CSRF protection of *all* endpoints which expect a Content-Type of `multipart/form-data`
This could be overridden in production-like environments with:
`play.filters.csrf.contentType.whiteList = ["application/xml", "application/json"]`

CDSID-1007 Temporary Fix for Tests

---

app/views/upload_your_files.scala.html

Add a label for file upload page because it was failing accessibility

---

app/Module.scala
app/connectors/Cache.scala
app/controllers/StartController.scala
app/controllers/actions/CacheDeleteAction.scala
app/views/components/submit_button.scala.html
app/views/start.scala.html
conf/app.routes
test/connectors/MongoCacheConnectorSpec.scala
test/controllers/StartControllerSpec.scala
test/controllers/actions/CacheDeleteActionSpec.scala
test/controllers/actions/FakeActions.scala
test/views/StartSpec.scala

I've done some experimenting with implementing an Action to clear the cache.  I needed to add a new endpoint to cause this to be triggered so I created one (POST /start) which just ensures the user is logged in, clears the cache and then redirects to the first step (Contact Address).
Only tested manually so far with two users in two different browsers.

CEDS-2369 - implement cache clearance on start journey

---

build.sbt
project/plugins.sbt

Due to problem with simple-reactivemongo with sbt-plugin version 2.6.24 we need to stay with version 2.6.23.

CEDS-2380 Libraries upgrade for PRA

---

app/connectors/CdsFileUploadConnector.scala
app/connectors/CustomsDeclarationsConnector.scala
app/controllers/test/CustomsDeclarationsStubController.scala
build.sbt
project/build.properties
project/plugins.sbt

This version seems to be the last reliable version.
Higher versions contain some issues with importing a project. That would
need additional steps and workarounds to make it work.

CEDS-2659 Upgrade SBT to 1.3.6

---

app/config/AppConfig.scala
app/views/govuk_wrapper.scala.html
conf/application.conf
test/config/AppConfigSpec.scala

All frontend HMRC services need to implement a cookie banner and this
changes the way we setup GTM (Google Tag Manager) into our services.
This is a centralised HRMC approach.
The container "a" has been provided by Alex Stanton, our performance
analyst.

CEDS-2770 New GTM rollout approach

---

app/config/AppConfig.scala
app/views/components/phase_banner.scala.html
app/views/govuk_wrapper.scala.html
conf/application.conf
conf/messages
test/base/Injector.scala
test/base/SpecBase.scala
test/base/UnitViewSpec.scala
test/config/AppConfigSpec.scala
test/connectors/CdsFileUploadConnectorSpec.scala
test/views/components/PhaseBannerSpec.scala
test/views/matchers/ViewMatchers.scala

Phase Banner is implemented differently to other repositories,
due to this service not being moved to `govuk` design system.
As much as I would like to have all Exports UI services aligned,
this change would involve too much time to be performed 'by 
the way'.

CEDS-2746 Add phase_banner view component

---

app/config/AppConfig.scala
app/views/components/phase_banner.scala.html
conf/application.conf
run-contact-frontend-sm_local.sh
test/views/components/PhaseBannerSpec.scala

There are 2 issues that are fixed in this PR:
1. `backURL` should have capitalized 'URL'
2. In other environments, the link to `contact-frontend` was incorrect.
It should be using url, similarly to how we link to Movements in
Declarations service.

CEDS-2746 Fix contact-frontend url

---

conf/application.conf

ws.timeout.request and ws.timeout.connection are already being overridden with a default value by the bootstrap library. 
They would also be overridden by app-config-common since we don't have this configured in the environment configs, so it's my understanding we haven't had these values applied to the service for a while now. 
see [blogpost](https://confluence.tools.tax.service.gov.uk/display/TEC/2020/12/01/Cleanup+deprecated+Play+framework+configuration+keys)

CEDS-2897 remove deprecated config

---

app/views/components/button_link.scala.html
app/views/upload_error.scala.html
conf/app.routes
conf/messages
test/views/UploadErrorSpec.scala

The previous content was not making it clear to the user on what might
have gone wrong, or what should they try to do next.
The new page contains a button that takes the user to the start page of
the service.

CEDS-2762 Change content for Upload Error page

---

app/views/start.scala.html
test/views/StartSpec.scala

This is a repetition of the GovUK page.
As per Liz's suggestion.

CEDS-2937 Remove first paragraph from Start page

---

app/config/AppConfig.scala
app/config/ExternalServicesConfig.scala
app/controllers/UnverifiedEmailController.scala
conf/application.conf
test/base/AppConfigMockHelper.scala
test/config/AppConfigSpec.scala
test/config/ExternalServiceConfigSpec.scala
test/controllers/UnverifiedEmailControllerSpec.scala

Use the 'url' section in the config to provide
the url as a relative link in the MDTP
environments.

[CEDS-2978] Fix Email Frontend Link Config

---

app/controllers/HowManyFilesUploadController.scala
app/controllers/MrnEntryController.scala
app/controllers/UnverifiedEmailController.scala
app/views/mrn_access_denied.scala.html
conf/app.routes
test/controllers/MrnEntryControllerSpec.scala
test/forms/mappings/ContactDetailsMappingSpec.scala
test/views/MrnAccessDeniedSpec.scala

As part of the usability improvements we are allowing the link
to SFUS from the Exports UI to include the MRN of the declaration
to pre-populate that field and remove the need for the user
to re-type it.

[CEDS-2821] Receiving MRN via URL param to skip entry page

---

test/base/Injector.scala

Unit tests make use of Injector trait which creates new application
every time the trait is initialized. This results in hundreds of
connections being created every time all tests are run.
Application instance that was created in Injector trait is not possible
to be overridden so there should be no downsides of having a single
instance for all tests.

BAU Decrease number of Mongo connections in tests

---

app/controllers/UploadYourFilesReceiptController.scala
app/views/upload_your_files_confirmation.scala.html
conf/messages
test/base/FilesUploadedSpec.scala
test/controllers/ControllerSpecBase.scala
test/controllers/UploadYourFilesReceiptControllerSpec.scala
test/views/UploadYourFilesConfirmationSpec.scala
test/views/UploadYourFilesReceiptSpec.scala

Adding new confirmation page to SFUS for when the
3110 TWSM feature flag is enabled (whilst retaining the
old receipt page for when disabled).

[CEDS-3053] 3110 Draft SFUS confirmation page update

---

conf/application.conf

This is to make local development and testing easier.
The flag is overridden to disabled in base configuration for
environments.

BAU Enabled secureMessaging feature flag

---

app/controllers/MrnEntryController.scala
app/views/mrn_entry.scala.html
test/controllers/MrnEntryControllerSpec.scala
test/views/MrnEntrySpec.scala

Fix the landing page when clicking the "Back" link on the "MRN Entry" page.
- Secure Messaging flag **disabled** => "Start" page
- Secure Messaging flag **enabled** => "Choice" page

CEDS-3027 Fix the "Back" link on the "MRN Entry" page

---

app/controllers/ChoiceController.scala
app/controllers/MrnEntryController.scala
app/controllers/SecureMessagingController.scala
app/models/FileUploadAnswers.scala
app/views/components/gds/navigationBanner.scala.html
app/views/contact_details.scala.html
app/views/messaging/partial_wrapper.scala.html
conf/app.routes
test/controllers/MrnEntryControllerSpec.scala
test/controllers/SecureMessagingControllerSpec.scala
test/views/ContactDetailsSpec.scala
test/views/UploadYourFilesSpec.scala
test/views/messaging/PartialWrapperSpec.scala

Added a new query string parameter of refererUrl to the
two GET mrn_entry endpoints. If passed this refererUrl
is saved in cache and used to populate the backUrl
value of the mrn_entry page.
Added this query string parameter to the link taking the 
user from the message page to the mrn_entry page.

[CEDS-3098] Custom back button redirect on mrn page

---

app/views/choice_page.scala.html
app/views/helpers/ErrorMapper.scala
app/views/messaging/inbox_choice.scala.html
test/views/ChoicePageSpec.scala
test/views/messaging/InboxChoiceSpec.scala

When the user fails to select an option in a radio
button form field, the error box displayed at the top
of the page should contain a link that when clicked
takes the user to that particular form field.
The two new choice pages on SFUS contained this link
but it was not taking them to the form field (was not
highlighting the first radio option) due to the anchor
reference being wrong. This is now fixed

[CEDS-2946] Fix highlighting of form field error link

---

app/config/AppConfig.scala
app/controllers/MrnEntryController.scala
app/controllers/actions/AuthAction.scala
app/utils/RefererUrlValidator.scala
conf/application.conf
test/base/AppConfigMockHelper.scala
test/config/AppConfigSpec.scala
test/controllers/MrnEntryControllerSpec.scala
test/utils/RefererUrlValidatorSpec.scala

To plug the security vulnerability that was picked up
in the pen test.
We now only allow relative urls that point to an
MDTP service that are on our allow list of services
and that only contain a limited set of ASCII chars.

[CEDS-3161] Sanitise accepted referer URL parameter

---

app/views/components/gds/pageTitle.scala.html
app/views/error_template.scala.html

Removing the heading legend as it isn't needed on most pages. Setting the default class to the most relevant for a h1.

CEDS-3947 - Legend fixes

---

app/views/upload_your_files.scala.html

Fixed the issue with Upscan returning 'Bad file' error notification.
Issue was a combination of the `name` attribute of the input form element not being set to 'file' and the unnecessary inclusion of a CSRF token hidden input element that Upscan was not expecting.

Ceds 4176 bug error fix

---

app/controllers/actions/AuthAction.scala
project/plugins.sbt
test/unit/controllers/actions/AuthActionSpec.scala

I did nothing practically, as `AuthAction` was already having a `recover` block :slightly_smiling_face:

CEDS-5392 Stop throwing exceptions on unauthorised users

---

app/assets/javascripts/validation.js
app/views/upload_your_files.scala.html

On initial page load there is no visually hidden error message in page. 
Set page title to include 'Error:' prefix if error is present on page. 
Focus is set to error summary link when error present. 
Stop disabling of form submit button (validation now only takes place when user clicks submit button). 
Added visually hidden 'Error:' prefix to form element error text.

CEDS-6153 Multiple issues with error handling on file upload page
